--Лабораторная работа 2
--Задание 1. Написание запросов к БД
--1.	Выведите информацию о заказчиках, сформировав два вычисляемых столбца: Фамилия заказчика и Имя заказчика. 
--select
--    substring(contactname from '^[^,]+') as "Фамилия заказчика", 
--    substring(contactname from '[^,]+$') as "Имя заказчика"     
--from
--    "Sales"."Customers";

--2.	На основе таблицы Employees напишите запрос, возвращающий таблицу из 3 столбцов: Фамилия сотрудника, Имя сотрудника, e-mail адрес. Столбец e-mail адрес должен быть сформирован в соответствие со следующим шаблоном: <имя>.<фамилия>@<названиеорганизации>.ru. Название организации придумайте сами! Полученные e-mail должны быть в нижнем регистре. Символы, недопустимые в адресе эл.почты, должны быть заменены нижним подчеркиванием.
--select lastname as "Фамилия сотрудника", 
--firstname as "Имя сотрудника",
--lower( 
--replace(firstname, ' ', '_')|| '.' || replace(lastname, ' ', '_')|| '@hsecompany.ru' ) as "e-mail адрес"
--from "HR"."Employees";
--3.	Напишите запрос, возвращающий набор уникальных записей из таблиц Employees и Customers. Результирующая таблица должна содержать 3 столбца: country, region, city. 
--select distinct country, region, city
--from "HR"."Employees"
--union 
--select distinct country, region, city
--from "Sales"."Customers";
--4.	На основании данных ТОЛЬКО таблицы Products (запрос только к одной таблице!) сформируйте таблицу из трех столбцов: Номер категории, Название продукта и Название категории. 
--Название категории должно выводиться в соответствии с ее номером: --1 -  'Beverages'; 2 - 'Condiments'; 3 - 'Confections'; 4 - 'Dairy Products'; 5 - 'Grains/Cereals'; 6 - 'Meat/Poultry';  7 - 'Produce'; 8 - 'Seafood'. Для категорий, не попавших в данный список, необходимо вернуть значение 'Other'
--select
--    categoryid as "Номер категории",
--    productname as "Название продукта",
--    case categoryid
--        when 1 then 'Beverages'
--        when 2 then 'Condiments'
--        when 3 then 'Confections'
--        when 4 then 'Dairy Products'
--        when 5 then 'Grains/Cereals'
--        when 6 then 'Meat/Poultry'
--        when 7 then 'Produce'
--        when 8 then 'Seafood'
--        else 'Other'
--    end as "Название категории"
--from
--    "Production"."Products";


--5.	Напишите запрос, возвращающий выборку следующего вида: ФИО сотрудника, месяц рождения сотрудника (название месяца, не число!!!!), год рождения сотрудника, полный адрес (Страна, город, регион)
--select
--    lastname || ' ' || firstname as "ФИО сотрудника",
--    to_char(birthdate, 'Month') as "Месяц рождения сотрудника", 
--    to_char(birthdate, 'YYYY') as "Год рождения сотрудника",
--    concat(country, ', ', city, ', ', region)  as "Полный адрес"
--from
--    "HR"."Employees";
--6.	Напишите запрос, возвращающий следующие данные о сотрудниках: номер сотрудника, фамилия сотрудника, дата рождения и вычисляемый столбец «ДР». Вычисляемый столбец должен содержать 1- если дня рождения еще не было, или 0 – если день рождения уже прошел. Отсортируйте результирующую выборку таким образом, чтобы работники у которых еще не было дня рождения были сверху, причем в порядке «приближения» дня рождения.
--select 
--	empid as "Номер сотрудника",
--	lastname as "Фамилия сотрудника",
--	birthdate as "Дата рождения сотрудника",
--	case  
--	when date_part('month', birthdate)<date_part('month', current_date) or  
--	(date_part('month', birthdate)=date_part('month', current_date) and date_part('day', birthdate)<date_part('day', current_date)) then 1
-- 	else 0
--	end as "ДР"
--from "HR"."Employees";

--Задание 2. Использование фильтрации 
--1.	Выведите из таблицы, содержащей сведения о заказах строки с 51 по 100, упорядоченные по дате заказа
--select *
--from ( select * from "Sales"."Orders" limit 50 offset 50)
--order by orderdate asc;
--2.	Отобразите поставщиков, у которых отсутствует факс
--select *
--from "Sales"."Customers"
--where fax is null or fax='';
--3.	Выведите название и цену продуктов, при условии, что цена находится в диапазоне от 100 до 250.
--select productname, unitprice 
--from "Production"."Products"
--where unitprice::numeric>=100 and unitprice::numeric<=250;
--4.	Напишите запрос, возвращающий список работников мужского пола, работающие менеджерами в Лондоне.
--select *
--from "HR"."Employees"
--where lower(titleofcourtesy) in ('mr.', 'mr', 'dr.') and title='Sales Manager' and city='London';
--5.	Выведите все заказы, сделанные (оформленные) после 10 апреля 2008 года
--select *
--from "Sales"."Orders"
--where shippeddate>'2008-04-10'::date;
--6.	Напишите запрос, извлекающий запись о сотруднике с номером телефона (206) 555-0100
--select *
--from "HR"."Employees"
--where phone='(206) 555-0100';
--7.	Выведите заказчиков с именами кроме “Linda”, “Robert”, “Ann”, “Venky”
--select *
--from "HR"."Employees"
--where firstname not in ('Linda', 'Robert', 'Ann', 'Venky');
--8.	Выведите информацию о заказчиках, сформировав два вычисляемых столбца: Фамилия заказчика и Имя заказчика. В результирующую выборку должны попасть только те заказчики, чье имя начинается либо на букву "P" либо на букву "M", а фамилия при этом начинается либо на “S” либо на “K”. Фильтрация должна производится на исходных данных столбца (не на вычисляемом выражении) 
--select
--    substring(contactname from '^[^,]+') as "Фамилия заказчика", 
--    substring(contactname from '[^,]+$') as "Имя заказчика"     
--from
--    "Sales"."Customers"
--where (substring(contactname from '[^,]+$') like ' P%' or substring(contactname from '[^,]+$') like ' M%')
--      and (substring(contactname from '^[^,]+') like 'S%' or substring(contactname from '^[^,]+') like 'K%') 
--9.	Выведите заказчиков, чьи контактные данные состоят из двух и более частей. 
--select *
--from "Sales"."Customers"
--where contactname like '% %';
