
--Лабораторная 8 Дополнительные возможности
--создания таблиц

--Задание 1
--Реализуйте следующее решение: Необходимо создать секционированную таблицу sales в
--соответствии с приведенной схемой секционирования.
--1) Секционированная таблица и ее секции должны размещаться в схеме partitions
create schema partitions;

create table partitions.sales (
    Trans_id int not null,
    Date date not null,
    region varchar(15) not null)
partition by range (Date);

create table partitions.sales_jan25
partition of partitions.sales
for values from ('2025-01-01') to ('2025-01-31')
partition by list (region);

create table partitions.sales_feb25
partition of partitions.sales
for values from ('2025-02-01') to ('2025-02-28')
partition by list (region);

create table partitions.sales_mar25
partition of partitions.sales
for values from ('2025-03-01') to ('2025-03-31')
partition by list (region);


create table partitions.sales_jan_usa
partition of partitions.sales_jan25
for values in ('usa');
create table partitions.sales_jan_asia
partition of partitions.sales_jan25
for values in ('asia');
create table partitions.sales_jan_europe
partition of partitions.sales_jan25
for values in ('europe');

create table partitions.sales_feb_usa
partition of partitions.sales_feb25
for values in ('usa');
create table partitions.sales_feb_asia
partition of partitions.sales_feb25
for values in ('asia');
create table partitions.sales_feb_europe
partition of partitions.sales_feb25
for values in ('europe');

create table partitions.sales_mar_usa
partition of partitions.sales_mar25
for values in ('usa');
create table partitions.sales_mar_asia
partition of partitions.sales_mar25
for values in ('asia');
create table partitions.sales_mar_europe
partition of partitions.sales_mar25
for values in ('europe');
--2) Добавьте в таблицу данные и проверьте корректность их размещения в таблицах-секциях.
--3) Приведите проверочный запрос

insert into partitions.sales values
(1, '2025-01-01', 'usa'), (2, '2025-01-01', 'europe'), (3, '2025-01-23', 'asia'),
(4, '2025-02-01', 'usa'), (5, '2025-02-01', 'europe'), (6, '2025-02-05', 'asia'),
(7, '2025-03-11', 'usa'), (8, '2025-03-21', 'europe'), (9, '2025-03-23', 'asia');

select tableoid::regclass, * 
from partitions.sales;
--Задание 2
--Добавьте в таблицу новую секцию - апрель 2025 года. Для этого:
--1) Создайте новую таблицу

create table partitions.sales_apr25 (
like partitions.sales 
including defaults including constraints);

alter table partitions.sales_apr25 
add constraint date_c
check (Date >= '2025-04-01' and Date <= '2025-04-30');
--2) Добавьте в нее данные о продажах за апрель

insert into partitions.sales_apr25 values
(10, '2025-04-01', 'usa'), (11, '2025-04-15', 'europe'), (11, '2025-04-25', 'asia'),
(12, '2025-04-11', 'usa'), (13, '2025-04-12', 'europe'), (14, '2025-04-05', 'asia');


--3) Подключите данную таблицу в виде секции к таблице Sales
alter table partitions.sales 
attach partition partitions.sales_apr25
for values from ('2025-04-01') to ('2025-04-30');
--Задание 3
--1 Отключите от таблицы секцию – jan25.
alter table partitions.sales detach partition partitions.sales_jan25;

--2 Отключаемые секции должны становиться частью таблицы –sales_arhive

create table partitions.sales_archive (
	Trans_id int not null,
    Date date not null,
    region varchar(15) not null
);

insert into partitions.sales_archive 
select * from partitions.sales_jan25;

--2)Наследование таблиц
--Задание 1 Необходимо реализовать возможность хранения информации о событиях в системе,
--разделенной по месяцам.
--1 В схеме example1 создайте таблицу logging со следующей структурой:

create schema example1;

create table example1.logging (
    id integer generated by default as identity(start with 1 increment by 1) primary key,  
    event_name character varying(100) not null,
    start_time timestamp(6) without time zone not null,
    end_time timestamp(6) without time zone not null
);


--2 Заполните таблицу событиями за 2022 год.

-- Заполняем таблицу событиями за 2022 год
insert into example1.logging (event_name, start_time, end_time) values
('Log in', '2022-01-11 03:26:11', '2022-01-11 03:26:13'),
( 'Log out', '2022-02-03 12:11:17', '2022-02-03 12:11:18'),
( 'Upload file xml', '2022-02-06 16:14:28', '2022-02-06 16:14:59'),
( 'Delete data', '2022-01-05 23:01:55', '2022-01-05 23:01:58');

--a. Убедитесь, что данные успешно сохранены
select * from example1.logging;
--3 Создайте дочернюю таблицу регистрации january_log_2023, которая наследует поля из
--родительской таблицы logging.
--b. Таблица должна позволять регистрировать события, которые начались в январе
--2023 года (start_time).

create table example1.january_log_2023 (
    constraint date_constr check (start_time >= '2023-01-01' and 
    start_time <= '2023-01-31')) 
inherits (example1.logging);

--4 Унаследовали ли дочерняя таблица свойство IDENTITY столбца id родительской таблицы?
--5 Заполните таблицу регистрации событиями за январь 2023 года:
insert into example1.january_log_2023 values
(1, 'Log in', '2023-01-11 03:26:11', '2023-01-11 03:26:13'),
(2, 'Log out', '2023-01-03 12:11:17', '2023-01-03 12:11:18'),
(3, 'Upload file xml', '2023-01-06 16:14:28', '2023-01-06 16:14:59'),
(4, 'Delete data', '2023-01-05 23:01:55', '2023-01-05 23:01:58');
--6 Создайте дочернюю таблицу регистрации february_log_2023, которая наследует поля из
--родительской таблицы logging.
--a. Таблица должна позволять регистрировать события, которые начались в феврале
--2023 года (start_time).
--b. Таблица должна содержать дополнительный столбец user_name (для сохранения
--информации о зарегистрировавшем событие пользователе)
create table example1.february_log_2023 (
    user_name varchar(50),
    constraint check_date_feb check (start_time >= '2023-02-01' and start_time <= '2023-02-28')
) inherits (example1.logging);


--7 Заполните таблицу регистрации событиями за февраль 2023 года. В качестве значений
--столбца user_name используйте имя пользователя текущего сеанса
--c. Убедитесь, что данные успешно сохранены

insert into example1.february_log_2023 values
( 17, 'Log in', '2023-02-11 03:26:11', '2023-02-11 03:26:13', current_user),
( 27, 'Log out', '2023-02-03 12:11:17', '2023-02-03 12:11:18', current_user),
( 37, 'Upload file xml', '2023-02-06 16:14:28', '2023-02-06 16:14:59', current_user),
( 47, 'Delete data', '2023-02-05 23:01:55', '2023-02-05 23:01:58',current_user);

select * from example1.february_log_2023;
--8 Проверьте возможность получения данных через родительскую таблицу
--a. Сохраняется ли уникальность в столбце id? Почему?
select * from example1.logging;

-- да, в родительской таблицы данные тоже есть
--нет, уникальность id не сохраняется, так как на дочерние таблицы
--не распространяется ограничение уникальности

--9 Удалите записи из таблицы logging. Остались ли записи в дочерних таблицах?

delete from example1.logging;

select * from example1.january_log_2023;
select * from example1.february_log_2023;

--данные не остались

--10 Удалите таблицу.
drop table example1.january_log_2023;
drop table example1.february_log_2023;
drop table example1.logging;
--Задание 2
--1 Создайте таблицу logging со следующей структурой
create table example1.logging (
    id integer not null primary key ,  
    event_name character varying(100) not null,
    start_time timestamp(6) without time zone not null,
    end_time timestamp(6) without time zone not null
);
--2 Заполните таблицу событиями за 2022 год.

insert into example1.logging values
( 1, 'Log in', '2022-02-11 03:26:11', '2022-02-11 03:26:13'),
( 2, 'Log out', '2022-02-03 12:11:17', '2022-02-03 12:11:18'),
( 3, 'Upload file xml', '2022-02-06 16:14:28', '2022-02-06 16:14:59'),
( 4, 'Delete data', '2022-02-05 23:01:55', '2022-02-05 23:01:58');
--3 По аналогии с заданием 1 создайте 2 дочерних таблицы - january_log_2023 и
--february_log_2023
--a. Какие свойства столбца id унаследовали дочерние таблицы от родительской
--таблицы? Ответ: все, кроме того, что id - PK

create table example1.january_log_2023 (
    constraint date_constr check (start_time >= '2023-01-01' and 
    start_time <= '2023-01-31')) 
inherits (example1.logging);

create table example1.february_log_2023 (
    user_name varchar(50),
    constraint check_date_feb check (start_time >= '2023-02-01' and start_time <= '2023-02-28')
) inherits (example1.logging);

select * from example1.february_log_2023;

--4 Заполните таблицы данными.
--a. Сохраняется ли уникальность значений в столбце id? Ответ: нет
insert into example1.february_log_2023 values
( 1, 'Log in', '2023-02-11 03:26:11', '2023-02-11 03:26:13', current_user),
( 2, 'Log out', '2023-02-03 12:11:17', '2023-02-03 12:11:18', current_user),
( 3, 'Upload file xml', '2023-02-06 16:14:28', '2023-02-06 16:14:59', current_user),
( 3, 'Delete data', '2023-02-05 23:01:55', '2023-02-05 23:01:58',current_user);

insert into example1.january_log_2023 values
(1, 'Log in', '2023-01-11 03:26:11', '2023-01-11 03:26:13'),
(2, 'Log out', '2023-01-03 12:11:17', '2023-01-03 12:11:18'),
(3, 'Upload file xml', '2023-01-06 16:14:28', '2023-01-06 16:14:59'),
(3, 'Delete data', '2023-01-05 23:01:55', '2023-01-05 23:01:58');
--5 Используя запрос к таблице logging измените наименование события 'Log in' на
--'Log in user'
update example1.logging 
set event_name = 'Log in user' 
where event_name = 'Log in';

--a. Записи в каких таблицах изменились? Ответ: во всех, и в родительской, и в дочерних
select * from example1.january_log_2023
where event_name='Log in user' ;
select * from example1.february_log_2023
where event_name='Log in user' ;

--6 Измените наименование события 'Upload file xml' на 'Upload file json' только в
--таблице february_log_2023.
update only example1.february_log_2023 
set event_name = 'Upload file json' 
where event_name = 'Upload file xml';
--a. Убедитесь, в корректности выполненных изменений
select * from example1.january_log_2023
where event_name='Upload file json'; --пусто
select * from example1.february_log_2023
where event_name='Upload file json' ; --изменения внесены

--7 Удалите ВСЕ события ТОЛЬКО из родительской таблицы
--a. Убедитесь, в корректности выполненных изменений
delete from only example1.logging;

select * from example1.logging;
select * from example1.february_log_2023;
select * from example1.january_log_2023;
